#!/bin/bash

echo "Compiling  ------"
javac *.java
echo "Running ---------"
java CompareQuadPoly 1 3 1 2 3 1
java CompareQuadPoly 3 2 1 3 2 2
java CompareQuadPoly 3 2 1 3 1 1
java CompareQuadPoly 3 3 3 3 3 3
