#!/bin/bash

echo "Initialising databases"


(
	echo "start transaction;"
	echo "drop table if exists address;"
	echo "create table address("
	echo "  id INT AUTO_INCREMENT,"
	echo "  name VARCHAR(50) UNIQUE,"
	echo "  email VARCHAR(150),"
	echo "  PRIMARY KEY(id)"
	echo ");"
	echo "insert into address (name,email)"
	echo "values ('James','james@james.com'),"
	echo "       ('Max','max@james.com');"
	echo "commit;"
)|
mysql -h dbhost.cs.man.ac.uk -u mbax3jp2 -p mbax3jp2 --password="fy18qp18mys"

echo "Done"