#!/bin/bash

echo "Compiling  ------"
javac *.java
echo "Running ---------"
java CompareQuadPoly 1 2 3 2 3 1
java CompareQuadPoly 3 2 1 3 2 1
java CompareQuadPoly 3 2 1 1 2 3
java AddQuadPoly 6 4 2 3 2 1
java AddQuadPoly -6 4 2 3 2 1
java AddQuadPoly 3 3 3 -3 -3 -3
java AddQuadPoly 1 1 1 0 0 0
